services:
  mongodb:
    image: mongo:7
    container_name: tp_mongodb_kaki
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: tp_jwt_mongodb
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
      - mongo_data:/data/db

  app:
    build: ./app
    container_name: tp_node_app_kaki
    restart: unless-stopped
    ports:
      - "8009:8009"
    environment:
      PORT: 8009
      MONGO_URI: mongodb://mongodb:27017/tp_jwt_mongodb
      JWT_SECRET: ca_c_est_le_jwt_secret_en_vrai_si_tu_le_trouves_tes_un_crack_et_je_te_suce
      JWT_EXPIRES_IN: 15m
    depends_on:
      - mongodb

volumes:
  mongo_data: